### ISSUE TITLE
Current industry jobs doesn't populate

### ISSUE THREAD

**Issue by zductiv** [EVEIPH/EVE-IPH#100] opened 2018-06-08 11:08 UTC
Industry jobs are not shown in the current industry jobs window.

![eve isk per hour_2018-06-08_18-59-49](https://user-images.githubusercontent.com/8939440/41154880-3986d8be-6b4e-11e8-82d9-dd5ae2384d9b.png)

The first characters number of jobs is correctly reported but details are not shown in the window.
The second characters number of jobs is NOT correctly reported (should be 9 of 9), and again, details are not shown in the window.

**Comment by Zifrian** [comment] 2018-07-02 02:02
Are the characters in an NPC corporation by chance?

**Comment by zductiv** [comment] 2018-07-02 11:44
The details seem to be correctly added to industry_jobs table in the db if that helps.

**Comment by Zifrian** [comment] 2018-07-02 19:18
All corp jobs?

**Comment by Zifrian** [comment] 2018-07-04 02:14
I'm going to work on this form this weekend and make it a bit less flakey.

**Comment by ben-abraham** [comment] 2018-07-04 23:43
Investigated this a bit. Looks to be that the industry jobs when installed in an play station, have a unique Location ID tied to the Asset entry of the station they are installed in.

So Industry Job (LocationID) -> (AssetID) Asset (LocationID) -> (SystemID) SolarSystem
I'm working on adjusting the SQL to handle this case cleanly (using names of the system/player station/possibly container or division if possible).

The quick fix would be to simple make the join to the stations table a LEFT JOIN and then coalesce the null column to something like "Player Station" or something of the sort.

**Comment by Zifrian** [comment] 2018-07-04 23:54
OK, that's certainly possible. All my stuff is in NPC stations that I've just noticed. All the other indicators I've seen earlier pointed to it just not being updated but zductive said the data was in the table. I'll go install something in a structure and see what the deal is. Thanks for looking into it.

**Comment by ben-abraham** [comment] 2018-07-05 05:03
So the /corporations/<id>/facilities and /corporations/<id>/structures endpoints will give the proper details we are looking for with the ID's we have (along with other useful metadata such as station name among other things.)
However, I realized that if the station the job is installed into is not owned by the player's corp (ie. public station), then that endpoint isn't going to show the details for that station.

For other/public stations, the /universe/structures/<id> endpoint can work for detail grabbing, with the only caveat being needing to make a new table to hold this info. (But since it won't really change, it should be safe to grab once/infrequently)


The relationship I mentioned previously in the assets table is listed as ID 27, which is the type "Office" basically saying that the corp's office at the station is essentially it's own unique location that all the assets are assigned to when in corp hangars.
Additionally, I queued up a job on my character with separate input/output hangars, but this information doesn't seem to be present in the API

![image](https://user-images.githubusercontent.com/793454/42303062-0bcd68d0-7fed-11e8-9192-60d55de995e7.png)

In that image the ...0394 ID's under facilityID and locationID are the ID for my structure, where as the ...9772 ID under blueprintLocationID and ouptputLocationID are the ID of the office object assigned to the structure.

All that said, my suggestion would be to just pull API details from /universe/structure/<id> every time an un-searched ID is found in one of those columns. However, there is still the issue of the separate office ID, since most people will not have that entry in their Assets table (only reason I had it in mine I believe is because I installed the office myself) and I have not found anything in the API that looks like it can return that information about any/all stations the corp has access to. The closes thing I can find is doing a query agains /corporations/assets for specfically TypeID 27, but unsure of how that would work with non-CEO/admin of corp querying that.

That was a long ramble, I hope there was some useful information in there :)

**Comment by Zifrian** [comment] 2018-07-05 11:45
That all verified what I found too. The issue is that ccp won’t give us names or locations of structures. Same issue comes up in the market prices.

The more annoying issue is that data pulls for structures from ESI are pretty slow. They removed some data from a few apis that requires me to look static data up via web call and it’s slow. (I could look it up before an update and store it but I’m reaching data limits on the db to host on github).

I’m going to go the simple route and put in ‘unknown’ or something for now since I think I’d you had something in an array it wouldn’t show the location either.

**Comment by ben-abraham** [comment] 2018-07-05 20:36
Agreed.

Currently the way the sql is written, you can just swap the join on the location table to a LEFT JOIN and the existing query will just show "Unknown" since you already have that fallback in your SQL (this does require a bit of restructuring of the query since it uses the `WHERE A.id = B.id` method of joining tables vs. JOIN syntax, but I have a testing change of this already if you'd like to see that)

**Closed as completed** 2018-07-11 13:25 UTC
