### ISSUE TITLE
Last stage of composite reaction uses ME 10 for calculation

### ISSUE THREAD

**Issue by seenkley** [EVEIPH/EVE-IPH#188] opened 2023-11-25 19:24 UTC
Hey,
recently I always have the issue, that I have to little materials to craft everything when using IPH.
After digging into it, I discovered that IPH  treats the last stage (some, not all) of an reaction (e.g. Crystalline Carbonide,...) as a normal blueprint instead of an reaction and therefore uses a material efficiency modifier of 10 - which doesn't work. 

![image](https://github.com/EVEIPH/EVE-IPH/assets/12306801/aa519a6b-96cd-4999-b766-782ad8020ff2)

In the above example I used the Ishtar as product with 20 runs.

Not sure if this is a misconfiguration on my end or a bug though.

(I'm using version: 5.0.8684.40312)

**Comment by Zifrian** [comment] 2023-12-02 04:39
Can you share a screenshot of the BP window? I'm not able to reproduce.

**Comment by seenkley** [comment] 2023-12-03 09:05
sure :)

![image](https://github.com/EVEIPH/EVE-IPH/assets/12306801/9e1b05f0-1880-45ee-b388-fe8bff5d00ea)

Also adding the shopping list, in case it helps.
[Shopping List - 12032023.txt](https://github.com/EVEIPH/EVE-IPH/files/13538446/Shopping.List.-.12032023.txt)

**Comment by Zifrian** [comment] 2023-12-04 02:15
Hmm, still not able to reproduce. Can you send me the details on the manufacturing facility and component manufacturing facility? I wonder if it's something to do with the rigs installed.

**Comment by Zifrian** [comment] 2023-12-06 03:42
This is fixed in Build 5.0.8739.40624.

**Closed by Zifrian** 2023-12-06 03:42 UTC
