### ISSUE TITLE
IPH crashes if the shopping list is sorted and you change the items

### ISSUE THREAD

**Issue by Regner** [EVEIPH/EVE-IPH#15] opened 2015-11-11 08:40 UTC
Repro:
* Add something to the shopping list
* Change the quantity in the items to be built, see it works
* Sort by the total cost column
* Change the quantity again
* Notice crash :(

**Comment by Zumochi** [comment] 2015-11-11 13:10
Followed reproduction steps and had the same issue.

**Comment by Zifrian** [comment] 2015-11-11 22:24
Awesome, thanks for the repro steps. Others have had this error too and I couldn't reproduce it. I'll get it fixed soon.

**Comment by Regner** [comment] 2015-11-11 23:39
Glad to be of help. :)

**Comment by Zumochi** [comment] 2015-11-13 08:36
This issue also applies to the blueprints tab. Sort by total value, change number of runs, crash.

**Comment by Zifrian** [comment] 2015-11-14 21:36
Bug fixed in 7a27f173b019053da9b3aa0808810729d2878594.
Please close issue. Thanks

**Closed** 2015-11-14 21:36 UTC

**Comment by Regner** [comment] 2015-11-14 23:37
Thanks for the amazingly quick fix. :)
