### ISSUE TITLE
Database locked

### ISSUE THREAD

**Issue by maxdp66** [EVEIPH/EVE-IPH#169] opened 2021-09-14 20:41 UTC
An Unhandled Exception has occured and EVE Isk per Hour will now close.

Please fill out the following information so I can reproduce the bug

**What is your Operating System?** 
Windows 11 (21H2 (OS Build 22000.184)

**What tab or screen did the error occur?** 
Database is locked

**What are the steps to reproduce the Error?** 
Update market data via marketer, save and update via CCP

**Web link to a screenshot of your error:** 
N/A

ERROR:

Source: EVE Isk per Hour
Message: An error occurred creating the form. See Exception.InnerException for details.  The error is: database is locked
database is locked
Raw Error Text: System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details.  The error is: database is locked
database is locked ---> System.Data.SQLite.SQLiteException: database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at EVE_Isk_per_Hour.DBConnection.ExecuteNonQuerySQL(String SQL)
   at EVE_Isk_per_Hour.ESI.UpdateIndustrySystemsCostIndex(Label& UpdateLabel, ProgressBar& PB)
   at EVE_Isk_per_Hour.frmMain..ctor()
   --- End of inner exception stack trace ---
   at EVE_Isk_per_Hour.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   at EVE_Isk_per_Hour.My.MyProject.MyForms.get_frmMain()
   at EVE_Isk_per_Hour.My.MyApplication.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
Error Tracking: UPDATE INDUSTRY_SYSTEMS_COST_INDICIES SET SOLAR_SYSTEM_NAME = 'Senda',ACTIVITY_ID = 1,ACTIVITY_NAME = 'Manufacturing',COST_INDEX = 0.004 WHERE SOLAR_SYSTEM_ID = 30020141 AND ACTIVITY_ID = 1

**Comment by Zifrian** [comment] 2021-09-15 02:41
This is a random error that pops up and I can't reproduce. Does it still happen for you? If you can reproduce the error step by step, that would be helpful to debug.

**Comment by sychris** [comment] 2021-12-16 09:16
my first run:
An Unhandled Exception has occured and EVE Isk per Hour will now close.

Please fill out the following information so I can reproduce the bug

What is your Operating System? 
What tab or screen did the error occur? 
What are the steps to reproduce the Error? 
Web link to a screenshot of your error: 
In addition to a screenshot, copy the data below and send to developer.

Source: EVE Isk per Hour
Message: An error occurred creating the form. See Exception.InnerException for details.  The error is: database is locked
database is locked
Raw Error Text: System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details.  The error is: database is locked
database is locked ---> System.Data.SQLite.SQLiteException: database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at EVE_Isk_per_Hour.DBConnection.ExecuteNonQuerySQL(String SQL)
   at EVE_Isk_per_Hour.ESI.UpdateIndustrySystemsCostIndex(Label& UpdateLabel, ProgressBar& PB)
   at EVE_Isk_per_Hour.frmMain..ctor()
   --- End of inner exception stack trace ---
   at EVE_Isk_per_Hour.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   at EVE_Isk_per_Hour.My.MyProject.MyForms.get_frmMain()
   at EVE_Isk_per_Hour.My.MyApplication.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
Error Tracking: INSERT INTO INDUSTRY_SYSTEMS_COST_INDICIES VALUES(30020141,'Senda',1,'Manufacturing',0.0015)

win 10 clicked the blueprint viewer button>clicked drone>maybe clicked light scout drones not sure but errored around there.

**Comment by Zifrian** [comment] 2023-04-23 00:48
I've added a bit more logic to catch this error. Closing for now.

**Closed by Zifrian** 2023-04-23 00:48 UTC
