### ISSUE TITLE
Update not possible

### ISSUE THREAD

**Issue by Genosse-X** [EVEIPH/EVE-IPH#111] opened 2018-07-04 11:36 UTC
https://i.gyazo.com/b8f35ed5c5ca34317f9d38cf6a1c8ef5.png

**Comment by Zifrian** [comment] 2018-07-04 12:52
What version do you have?

**Comment by Genosse-X** [comment] 2018-07-04 13:47
i have 4.0 and when i start, it want update, but it dont work. i have downloaded the whole file again, but its ist same size...

**Comment by Zifrian** [comment] 2018-07-04 13:53
Can you go to the %appdata% EVE IPH folder and send me the EVEIPH.log file? I can't do much with the screenshot. The updater works fine for me.

**Comment by Genosse-X** [comment] 2018-07-04 14:42
hi, there is no file https://i.gyazo.com/6b59d28b380210eb4e3e3a419e3b105e.png when i start the update.exe i get this https://i.gyazo.com/d6f7cd17a61e05d4da74d5793066f43f.png

**Comment by Zifrian** [comment] 2018-07-04 15:21
OK that's helpful. I pushed a patch. Try it now. Should be good to go.

**Comment by Genosse-X** [comment] 2018-07-04 15:57
ok now it work... but^^ now i try to add a character i press login, it redirict me to the login screen of eve, i enter  the credentials and then i get this: 
https://i.gyazo.com/1567ec9d8b29f96aba7321e13e341aec.png

and that is the header:
https://i.gyazo.com/2ca9deda7852b447c295951a922f2527.png

**Comment by ben-abraham** [comment] 2018-07-04 16:50
Secondary (scopes error) issue resolved with PR #110

**Comment by Zifrian** [comment] 2018-07-04 17:10
#110 was in this update. I'll see what's up.

**Comment by Zifrian** [comment] 2018-07-04 18:40
The issue is that your browser is changing spaces to %2520 when called. I thought it was in the code. I'm looking into options to fix it but right now the only thing you could try is switching your default browser and trying to log in that way.

**Comment by ben-abraham** [comment] 2018-07-04 22:46
%25 = "%" in url encoding, so %2520 = URLEncode("%20") which is URL encoded space. You are just seeing the URL double-encoded because it is being passed as a referer header into the other web call and therefore needs to be escape again, this is normal/expected.

As far as why the error is occurring, from the looks of it, it;s requesting a lot of scopes (looks to possibly be all of them). Maybe reducing this down to only the scopes explicitly required by the app might help or change things. You can leave all the scopes on the API key, and just change the list that the application has to save some time.

These were the scopes I used when setting up my account (which I re-tried today on the released update with Chrome and FF, both worked)


```
publicData
esi-skills.read_skills.v1
esi-assets.read_assets.v1
esi-characters.read_standings.v1
esi-characters.read_agents_research.v1
esi-industry.read_character_jobs.v1
esi-characters.read_blueprints.v1
esi-assets.read_corporation_assets.v1
esi-corporations.read_blueprints.v1
esi-industry.read_corporation_jobs.v1
esi-corporations.read_corporation_membership.v1
```

Hope this helps.

**Comment by Zifrian** [comment] 2018-07-04 23:52
Thanks, I read that the %2520 was double spaces...but the code should handle that anyway. Maybe it was a CrLF? I added that in my current code. I've also tested with all scopes and it works fine on my end.

**Comment by Genosse-X** [comment] 2018-07-05 02:09
i see there is an update.. i downloaded it and get same error.. can you maybe just show the link, that is hidden by clicking on this button? like in evernus https://i.gyazo.com/f3ab6e2420eb514b30bc5852c379b5e6.png

**Comment by Zifrian** [comment] 2018-07-05 11:48
Ok I’ll add something like that.

Where are you getting your scopes from though? Are you copying them from the registration page you made for IPH?

**Comment by Genosse-X** [comment] 2018-07-05 12:10
what do you mean? which scopes...

**Comment by Zifrian** [comment] 2018-07-05 15:42
The ones you are trying to register with. I’m trying to figure out why your scopes are somehow different. Are you copy and pasting them from the developer website into iph?

**Comment by Zifrian** [comment] 2018-09-09 02:00
In update Build 4.0.6825.38684, I added an option button to manually update. It will show up if you have problems logging in normally or if your request times out. Please enter a new issue if you still have problems logging in.

**Closed by Zifrian** 2018-09-09 02:00 UTC
